apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-tls
spec:
  provider: azure
  secretObjects: # k8s secret
  - secretName: tls-secret-csi-dev
    type: kubernetes.io/tls
    data: 
    - objectName: aks-ingress-cert # aks-cert-tls-dev # 
      key: tls.key
    - objectName: aks-ingress-cert # aks-cert-tls-dev # 
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: b3400c9a-848c-4436-94c4-bfa6360a7712
    keyvaultName: kvaksingressapp004 # the name of the AKV instance
    objects: |
      array:
        - |
          objectName: aks-ingress-cert
          objectType: secret
    tenantId: 16b3c013-d300-468d-ac64-7eda0820b6d3 # the tenant ID for KV
