# src: https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/docs/driver-parameters.md
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-blob
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # If set as "Delete" container would be removed after pvc deletion
  storageClassName: azureblob-fuse-premium
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: storage4aks013-container01
    volumeAttributes:
      resourceGroup: rg-aks-cluster
      storageAccount: storage4aks013
      containerName: "container01"
      # refer to https://github.com/Azure/azure-storage-fuse#environment-variables
      AzureStorageAuthType: MSI  # key, sas, msi, spn
      AzureStorageIdentityClientID: ""
      AzureStorageIdentityObjectID: ""
      AzureStorageIdentityResourceID: "/subscriptions/82f6d75e-85f4-434a-xxxxxxxxx/resourcegroups/rg-aks-cluster/providers/Microsoft.ManagedIdentity/userAssignedIdentities/identity-storage-account"
      MSIEndpoint: ""
      AzureStorageSPNClientID: ""
      AzureStorageSPNTenantID: ""
      AzureStorageAADEndpoint: ""
    nodeStageSecretRef:
      name: azure-secret
      namespace: default