apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
        effect: NoSchedule
      # - key: node-role.kubernetes.io/control-plane
      #   operator: Exists
      #   effect: NoSchedule
      # - key: node-role.kubernetes.io/master
      #   operator: Exists
      #   effect: NoSchedule
      # - key: CriticalAddonsOnly
      #   operator: Exists
      # - operator: Exists
      #   effect: NoExecute
