apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-blob-nfs
  labels:
    app: nginx
spec:
  serviceName: statefulset-blob-nfs
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: statefulset-blob-nfs
        image: mcr.microsoft.com/oss/nginx/nginx:1.19.5
        command:
        - "/bin/sh"
        - "-c"
        - while true; do echo $(date) >> /mnt/azureblob/data; sleep 60; done
        volumeMounts:
        - name: persistent-storage
          mountPath: /mnt/azureblob
  volumeClaimTemplates:
  - metadata:
      name: persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: azureblob-nfs-premium
    spec:
      accessModes: ["ReadWriteMany"]
      resources:
        requests:
          storage: 100Gi